//
//  SearchPresenter.swift
//  GameBro
//
//  Created by Ariel Theodore W on 11/08/20.
//  Copyright (c) 2020 ariltw. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic
{
  func presentSomething(response: Search.Something.Response)
}

class SearchPresenter: SearchPresentationLogic
{
  weak var viewController: SearchDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Search.Something.Response)
  {
    print("start presenter")
    let viewModel = Search.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
    print("stop presenter")
  }
}
