//
//  SearchInteractor.swift
//  GameBro
//
//  Created by Ariel Theodore W on 11/08/20.
//  Copyright (c) 2020 ariltw. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic
{
  func doSomething(request: Search.Something.Request)
}

protocol SearchDataStore
{
  //var name: String { get set }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore
{
  var presenter: SearchPresentationLogic?
  var worker: SearchWorker?
  var viewController: SearchViewController?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Search.Something.Request)
  {
    
  }
}
