//
//  SearchWorker.swift
//  GameBro
//
//  Created by Ariel Theodore W on 11/08/20.
//  Copyright (c) 2020 ariltw. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchWorker
{
  func doSomeWork()
  {
    print("start work")
    sleep(5)
    print("stop work")
  }
}
